### ISSUE TITLE
DFA from NFA class problem

### ISSUE THREAD

**Issue by scdekov** [sdht0/automata-from-regex#1]
hi, when i try to create new DFAfromNFA with arguement of constructor- object created with NFAfromRegex i get  "AttributeError: 'NFAfromRegex' object has no attribute 'getEClose'"
because this attribute is in Automata  class. How can i solve this problem.
Thank you!

**Comment by sdht0** [comment]
Hey. Checkout the cli.py file to see how to initialize the classes correctly.

Specifically, you need to pass the object returned by the getNFA() function.

**Comment by scdekov** [comment]
automata = NFAfromRegex("(ab)*")
dfa = DFAfromNFA(automata.getNFA())

this is my initialization of clases and i get error "AttributeError: 'dict' object has no attribute 'iteritems'"

Thank you for helping me man !

**Comment by sdht0** [comment]
Umm I am unable to reproduce the error you're getting. Make sure you are using python version 2.x.

You can verify the code works by running `python2 cli.py "(ab)*"`

**Comment by scdekov** [comment]
yes my mistake i was running it with python3 sorry and thank you again
