### ISSUE TITLE
use sign chars ( + - " ' )

### ISSUE THREAD

**Issue by mlibre** [sdht0/automata-from-regex#2]
how to use sign chars ( + - " ' ) in regular expression entry ?
Ex:  
"[a-zA-Z0-9]"
how to enter this ????
at first comes double qoutation the chars from a to z or A to Z or 0 - 9 and at last double qoutation again

**Comment by sdht0** [comment]
Hi. Support for character class is not implemented. So you can only use + \* . and ()

**Comment by mlibre** [comment]
ok. thanks
