### ISSUE TITLE
can you write down which algorithm used here ?

### ISSUE THREAD

**Issue by riyoua** [sdht0/automata-from-regex#6]

**Comment by sdht0** [comment]
Regex to NFA: https://en.wikipedia.org/wiki/Thompson%27s_construction
NFA to DFA: https://en.wikipedia.org/wiki/Powerset_construction

You can google to find more examples.

**Comment by riyoua** [comment]
thanks .. 
i have some problem with the "or" symbol ... 
--------------------------------
Regular Expression:  x(x|y)*|z

Failure: Symbol '|' is not allowed

**Comment by sdht0** [comment]
You have to use the '+' symbol instead of '|'

**Comment by riyoua** [comment]
thanks alot ...
